name: Testes Automatizados - API
on:
  push:
    branches: [ CI/CD ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependências
        run: |
          cd api
          npm install

      - name: Rodar testes de API
        run: |
          cd api
          npm test

      - name: Gerar relatório
        if: success()
        run: |
          cd api
          npm run generate-report
